/**
 * 資料來源:https://tw.portal-pokemon.com
 */
let data = [
  {
    id: "001",
    zukan_sub_id: 0,
    name: "妙蛙種子",
    pokemon_sub_name: "",
    weight: 6.9,
    height: 0.7,
    file_name: "./images/pokemons/001.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "002",
    zukan_sub_id: 0,
    name: "妙蛙草",
    pokemon_sub_name: "",
    weight: 13,
    height: 1,
    file_name: "./images/pokemons/002.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "003",
    zukan_sub_id: 0,
    name: "妙蛙花",
    pokemon_sub_name: "",
    weight: 100,
    height: 2,
    file_name: "./images/pokemons/003.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "003",
    zukan_sub_id: 1,
    name: "超級妙蛙花",
    pokemon_sub_name: "",
    weight: 155.5,
    height: 2.4,
    file_name: "./images/pokemons/003-1.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "004",
    zukan_sub_id: 0,
    name: "小火龍",
    pokemon_sub_name: "",
    weight: 8.5,
    height: 0.6,
    file_name: "./images/pokemons/004.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "005",
    zukan_sub_id: 0,
    name: "火恐龍",
    pokemon_sub_name: "",
    weight: 19,
    height: 1.1,
    file_name: "./images/pokemons/005.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "006",
    zukan_sub_id: 0,
    name: "噴火龍",
    pokemon_sub_name: "",
    weight: 90.5,
    height: 1.7,
    file_name: "./images/pokemons/006.png",
    pokemon_type_id: "fire,flying",
    pokemon_type_name: "火,飛行",
  },
  {
    id: "006",
    zukan_sub_id: 1,
    name: "超級噴火龍Ｘ",
    pokemon_sub_name: "",
    weight: 110.5,
    height: 1.7,
    file_name: "./images/pokemons/006-1.png",
    pokemon_type_id: "fire,dragon",
    pokemon_type_name: "火,龍",
  },
  {
    id: "006",
    zukan_sub_id: 2,
    name: "超級噴火龍Ｙ",
    pokemon_sub_name: "",
    weight: 100.5,
    height: 1.7,
    file_name: "./images/pokemons/006-2.png",
    pokemon_type_id: "fire,flying",
    pokemon_type_name: "火,飛行",
  },
  {
    id: "007",
    zukan_sub_id: 0,
    name: "傑尼龜",
    pokemon_sub_name: "",
    weight: 9,
    height: 0.5,
    file_name: "./images/pokemons/007.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "008",
    zukan_sub_id: 0,
    name: "卡咪龜",
    pokemon_sub_name: "",
    weight: 22.5,
    height: 1,
    file_name: "./images/pokemons/008.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "009",
    zukan_sub_id: 0,
    name: "水箭龜",
    pokemon_sub_name: "",
    weight: 85.5,
    height: 1.6,
    file_name: "./images/pokemons/009.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "009",
    zukan_sub_id: 1,
    name: "超級水箭龜",
    pokemon_sub_name: "",
    weight: 101.1,
    height: 1.6,
    file_name: "./images/pokemons/009-1.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "010",
    zukan_sub_id: 0,
    name: "綠毛蟲",
    pokemon_sub_name: "",
    weight: 2.9,
    height: 0.3,
    file_name: "./images/pokemons/010.png",
    pokemon_type_id: "bug",
    pokemon_type_name: "蟲",
  },
  {
    id: "011",
    zukan_sub_id: 0,
    name: "鐵甲蛹",
    pokemon_sub_name: "",
    weight: 9.9,
    height: 0.7,
    file_name: "./images/pokemons/011.png",
    pokemon_type_id: "bug",
    pokemon_type_name: "蟲",
  },
  {
    id: "012",
    zukan_sub_id: 0,
    name: "巴大蝶",
    pokemon_sub_name: "",
    weight: 32,
    height: 1.1,
    file_name: "./images/pokemons/012.png",
    pokemon_type_id: "bug,flying",
    pokemon_type_name: "蟲,飛行",
  },
  {
    id: "013",
    zukan_sub_id: 0,
    name: "獨角蟲",
    pokemon_sub_name: "",
    weight: 3.2,
    height: 0.3,
    file_name: "./images/pokemons/013.png",
    pokemon_type_id: "bug,poison",
    pokemon_type_name: "蟲,毒",
  },
  {
    id: "014",
    zukan_sub_id: 0,
    name: "鐵殼蛹",
    pokemon_sub_name: "",
    weight: 10,
    height: 0.6,
    file_name: "./images/pokemons/014.png",
    pokemon_type_id: "bug,poison",
    pokemon_type_name: "蟲,毒",
  },
  {
    id: "015",
    zukan_sub_id: 0,
    name: "大針蜂",
    pokemon_sub_name: "",
    weight: 29.5,
    height: 1,
    file_name: "./images/pokemons/015.png",
    pokemon_type_id: "bug,poison",
    pokemon_type_name: "蟲,毒",
  },
  {
    id: "015",
    zukan_sub_id: 1,
    name: "超級大針蜂",
    pokemon_sub_name: "",
    weight: 40.5,
    height: 1.4,
    file_name: "./images/pokemons/015-1.png",
    pokemon_type_id: "bug,poison",
    pokemon_type_name: "蟲,毒",
  },
  {
    id: "016",
    zukan_sub_id: 0,
    name: "波波",
    pokemon_sub_name: "",
    weight: 1.8,
    height: 0.3,
    file_name: "./images/pokemons/016.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "017",
    zukan_sub_id: 0,
    name: "比比鳥",
    pokemon_sub_name: "",
    weight: 30,
    height: 1.1,
    file_name: "./images/pokemons/017.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "018",
    zukan_sub_id: 0,
    name: "大比鳥",
    pokemon_sub_name: "",
    weight: 39.5,
    height: 1.5,
    file_name: "./images/pokemons/018.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "018",
    zukan_sub_id: 1,
    name: "超級大比鳥",
    pokemon_sub_name: "",
    weight: 50.5,
    height: 2.2,
    file_name: "./images/pokemons/018-1.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "019",
    zukan_sub_id: 0,
    name: "小拉達",
    pokemon_sub_name: "",
    weight: 3.5,
    height: 0.3,
    file_name: "./images/pokemons/019.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "019",
    zukan_sub_id: 1,
    name: "小拉達",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 3.8,
    height: 0.3,
    file_name: "./images/pokemons/019-1.png",
    pokemon_type_id: "dark,normal",
    pokemon_type_name: "惡,一般",
  },
  {
    id: "020",
    zukan_sub_id: 0,
    name: "拉達",
    pokemon_sub_name: "",
    weight: 18.5,
    height: 0.7,
    file_name: "./images/pokemons/020.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "020",
    zukan_sub_id: 1,
    name: "拉達",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 25.5,
    height: 0.7,
    file_name: "./images/pokemons/020-1.png",
    pokemon_type_id: "dark,normal",
    pokemon_type_name: "惡,一般",
  },
  {
    id: "021",
    zukan_sub_id: 0,
    name: "烈雀",
    pokemon_sub_name: "",
    weight: 2,
    height: 0.3,
    file_name: "./images/pokemons/021.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "022",
    zukan_sub_id: 0,
    name: "大嘴雀",
    pokemon_sub_name: "",
    weight: 38,
    height: 1.2,
    file_name: "./images/pokemons/022.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "023",
    zukan_sub_id: 0,
    name: "阿柏蛇",
    pokemon_sub_name: "",
    weight: 6.9,
    height: 2,
    file_name: "./images/pokemons/023.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "024",
    zukan_sub_id: 0,
    name: "阿柏怪",
    pokemon_sub_name: "",
    weight: 65,
    height: 3.5,
    file_name: "./images/pokemons/024.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "025",
    zukan_sub_id: 0,
    name: "皮卡丘",
    pokemon_sub_name: "",
    weight: 6,
    height: 0.4,
    file_name: "./images/pokemons/025.png",
    pokemon_type_id: "electric",
    pokemon_type_name: "電",
  },
  {
    id: "026",
    zukan_sub_id: 0,
    name: "雷丘",
    pokemon_sub_name: "",
    weight: 30,
    height: 0.8,
    file_name: "./images/pokemons/026.png",
    pokemon_type_id: "electric",
    pokemon_type_name: "電",
  },
  {
    id: "026",
    zukan_sub_id: 1,
    name: "雷丘",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 21,
    height: 0.7,
    file_name: "./images/pokemons/026-1.png",
    pokemon_type_id: "electric,psychic",
    pokemon_type_name: "電,超能力",
  },
  {
    id: "027",
    zukan_sub_id: 0,
    name: "穿山鼠",
    pokemon_sub_name: "",
    weight: 12,
    height: 0.6,
    file_name: "./images/pokemons/027.png",
    pokemon_type_id: "ground",
    pokemon_type_name: "地面",
  },
  {
    id: "027",
    zukan_sub_id: 1,
    name: "穿山鼠",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 40,
    height: 0.7,
    file_name: "./images/pokemons/027-1.png",
    pokemon_type_id: "ice,steel",
    pokemon_type_name: "冰,鋼",
  },
  {
    id: "028",
    zukan_sub_id: 0,
    name: "穿山王",
    pokemon_sub_name: "",
    weight: 29.5,
    height: 1,
    file_name: "./images/pokemons/028.png",
    pokemon_type_id: "ground",
    pokemon_type_name: "地面",
  },
  {
    id: "028",
    zukan_sub_id: 1,
    name: "穿山王",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 55,
    height: 1.2,
    file_name: "./images/pokemons/028-1.png",
    pokemon_type_id: "ice,steel",
    pokemon_type_name: "冰,鋼",
  },
  {
    id: "029",
    zukan_sub_id: 0,
    name: "尼多蘭",
    pokemon_sub_name: "",
    weight: 7,
    height: 0.4,
    file_name: "./images/pokemons/029.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "030",
    zukan_sub_id: 0,
    name: "尼多娜",
    pokemon_sub_name: "",
    weight: 20,
    height: 0.8,
    file_name: "./images/pokemons/030.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "031",
    zukan_sub_id: 0,
    name: "尼多后",
    pokemon_sub_name: "",
    weight: 60,
    height: 1.3,
    file_name: "./images/pokemons/031.png",
    pokemon_type_id: "poison,ground",
    pokemon_type_name: "毒,地面",
  },
  {
    id: "032",
    zukan_sub_id: 0,
    name: "尼多朗",
    pokemon_sub_name: "",
    weight: 9,
    height: 0.5,
    file_name: "./images/pokemons/032.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "033",
    zukan_sub_id: 0,
    name: "尼多力諾",
    pokemon_sub_name: "",
    weight: 19.5,
    height: 0.9,
    file_name: "./images/pokemons/033.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "034",
    zukan_sub_id: 0,
    name: "尼多王",
    pokemon_sub_name: "",
    weight: 62,
    height: 1.4,
    file_name: "./images/pokemons/034.png",
    pokemon_type_id: "poison,ground",
    pokemon_type_name: "毒,地面",
  },
  {
    id: "035",
    zukan_sub_id: 0,
    name: "皮皮",
    pokemon_sub_name: "",
    weight: 7.5,
    height: 0.6,
    file_name: "./images/pokemons/035.png",
    pokemon_type_id: "fairy",
    pokemon_type_name: "妖精",
  },
  {
    id: "036",
    zukan_sub_id: 0,
    name: "皮可西",
    pokemon_sub_name: "",
    weight: 40,
    height: 1.3,
    file_name: "./images/pokemons/036.png",
    pokemon_type_id: "fairy",
    pokemon_type_name: "妖精",
  },
  {
    id: "037",
    zukan_sub_id: 0,
    name: "六尾",
    pokemon_sub_name: "",
    weight: 9.9,
    height: 0.6,
    file_name: "./images/pokemons/037.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "037",
    zukan_sub_id: 1,
    name: "六尾",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 9.9,
    height: 0.6,
    file_name: "./images/pokemons/037-1.png",
    pokemon_type_id: "ice",
    pokemon_type_name: "冰",
  },
  {
    id: "038",
    zukan_sub_id: 0,
    name: "九尾",
    pokemon_sub_name: "",
    weight: 19.9,
    height: 1.1,
    file_name: "./images/pokemons/038.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "038",
    zukan_sub_id: 1,
    name: "九尾",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 19.9,
    height: 1.1,
    file_name: "./images/pokemons/038-1.png",
    pokemon_type_id: "ice,fairy",
    pokemon_type_name: "冰,妖精",
  },
  {
    id: "039",
    zukan_sub_id: 0,
    name: "胖丁",
    pokemon_sub_name: "",
    weight: 5.5,
    height: 0.5,
    file_name: "./images/pokemons/039.png",
    pokemon_type_id: "normal,fairy",
    pokemon_type_name: "一般,妖精",
  },
  {
    id: "040",
    zukan_sub_id: 0,
    name: "胖可丁",
    pokemon_sub_name: "",
    weight: 12,
    height: 1,
    file_name: "./images/pokemons/040.png",
    pokemon_type_id: "normal,fairy",
    pokemon_type_name: "一般,妖精",
  },
  {
    id: "041",
    zukan_sub_id: 0,
    name: "超音蝠",
    pokemon_sub_name: "",
    weight: 7.5,
    height: 0.8,
    file_name: "./images/pokemons/041.png",
    pokemon_type_id: "poison,flying",
    pokemon_type_name: "毒,飛行",
  },
  {
    id: "042",
    zukan_sub_id: 0,
    name: "大嘴蝠",
    pokemon_sub_name: "",
    weight: 55,
    height: 1.6,
    file_name: "./images/pokemons/042.png",
    pokemon_type_id: "poison,flying",
    pokemon_type_name: "毒,飛行",
  },
  {
    id: "043",
    zukan_sub_id: 0,
    name: "走路草",
    pokemon_sub_name: "",
    weight: 5.4,
    height: 0.5,
    file_name: "./images/pokemons/043.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "044",
    zukan_sub_id: 0,
    name: "臭臭花",
    pokemon_sub_name: "",
    weight: 8.6,
    height: 0.8,
    file_name: "./images/pokemons/044.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "045",
    zukan_sub_id: 0,
    name: "霸王花",
    pokemon_sub_name: "",
    weight: 18.6,
    height: 1.2,
    file_name: "./images/pokemons/045.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "046",
    zukan_sub_id: 0,
    name: "派拉斯",
    pokemon_sub_name: "",
    weight: 5.4,
    height: 0.3,
    file_name: "./images/pokemons/046.png",
    pokemon_type_id: "bug,grass",
    pokemon_type_name: "蟲,草",
  },
  {
    id: "047",
    zukan_sub_id: 0,
    name: "派拉斯特",
    pokemon_sub_name: "",
    weight: 29.5,
    height: 1,
    file_name: "./images/pokemons/047.png",
    pokemon_type_id: "bug,grass",
    pokemon_type_name: "蟲,草",
  },
  {
    id: "048",
    zukan_sub_id: 0,
    name: "毛球",
    pokemon_sub_name: "",
    weight: 30,
    height: 1,
    file_name: "./images/pokemons/048.png",
    pokemon_type_id: "bug,poison",
    pokemon_type_name: "蟲,毒",
  },
  {
    id: "049",
    zukan_sub_id: 0,
    name: "摩魯蛾",
    pokemon_sub_name: "",
    weight: 12.5,
    height: 1.5,
    file_name: "./images/pokemons/049.png",
    pokemon_type_id: "bug,poison",
    pokemon_type_name: "蟲,毒",
  },
  {
    id: "050",
    zukan_sub_id: 0,
    name: "地鼠",
    pokemon_sub_name: "",
    weight: 0.8,
    height: 0.2,
    file_name: "./images/pokemons/050.png",
    pokemon_type_id: "ground",
    pokemon_type_name: "地面",
  },
  {
    id: "050",
    zukan_sub_id: 1,
    name: "地鼠",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 1,
    height: 0.2,
    file_name: "./images/pokemons/050-1.png",
    pokemon_type_id: "ground,steel",
    pokemon_type_name: "地面,鋼",
  },
  {
    id: "051",
    zukan_sub_id: 0,
    name: "三地鼠",
    pokemon_sub_name: "",
    weight: 33.3,
    height: 0.7,
    file_name: "./images/pokemons/051.png",
    pokemon_type_id: "ground",
    pokemon_type_name: "地面",
  },
  {
    id: "051",
    zukan_sub_id: 1,
    name: "三地鼠",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 66.6,
    height: 0.7,
    file_name: "./images/pokemons/051-1.png",
    pokemon_type_id: "ground,steel",
    pokemon_type_name: "地面,鋼",
  },
  {
    id: "052",
    zukan_sub_id: 0,
    name: "喵喵",
    pokemon_sub_name: "",
    weight: 4.2,
    height: 0.4,
    file_name: "./images/pokemons/052.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "052",
    zukan_sub_id: 1,
    name: "喵喵",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 4.2,
    height: 0.4,
    file_name: "./images/pokemons/052-1.png",
    pokemon_type_id: "dark",
    pokemon_type_name: "惡",
  },
  {
    id: "053",
    zukan_sub_id: 0,
    name: "貓老大",
    pokemon_sub_name: "",
    weight: 32,
    height: 1,
    file_name: "./images/pokemons/053.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "053",
    zukan_sub_id: 1,
    name: "貓老大",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 33,
    height: 1.1,
    file_name: "./images/pokemons/053-1.png",
    pokemon_type_id: "dark",
    pokemon_type_name: "惡",
  },
  {
    id: "054",
    zukan_sub_id: 0,
    name: "可達鴨",
    pokemon_sub_name: "",
    weight: 19.6,
    height: 0.8,
    file_name: "./images/pokemons/054.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "055",
    zukan_sub_id: 0,
    name: "哥達鴨",
    pokemon_sub_name: "",
    weight: 76.6,
    height: 1.7,
    file_name: "./images/pokemons/055.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "056",
    zukan_sub_id: 0,
    name: "猴怪",
    pokemon_sub_name: "",
    weight: 28,
    height: 0.5,
    file_name: "./images/pokemons/056.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "057",
    zukan_sub_id: 0,
    name: "火爆猴",
    pokemon_sub_name: "",
    weight: 32,
    height: 1,
    file_name: "./images/pokemons/057.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "058",
    zukan_sub_id: 0,
    name: "卡蒂狗",
    pokemon_sub_name: "",
    weight: 19,
    height: 0.7,
    file_name: "./images/pokemons/058.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "059",
    zukan_sub_id: 0,
    name: "風速狗",
    pokemon_sub_name: "",
    weight: 155,
    height: 1.9,
    file_name: "./images/pokemons/059.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "060",
    zukan_sub_id: 0,
    name: "蚊香蝌蚪",
    pokemon_sub_name: "",
    weight: 12.4,
    height: 0.6,
    file_name: "./images/pokemons/060.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "061",
    zukan_sub_id: 0,
    name: "蚊香君",
    pokemon_sub_name: "",
    weight: 20,
    height: 1,
    file_name: "./images/pokemons/061.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "062",
    zukan_sub_id: 0,
    name: "蚊香泳士",
    pokemon_sub_name: "",
    weight: 54,
    height: 1.3,
    file_name: "./images/pokemons/062.png",
    pokemon_type_id: "water,fighting",
    pokemon_type_name: "水,格鬥",
  },
  {
    id: "063",
    zukan_sub_id: 0,
    name: "凱西",
    pokemon_sub_name: "",
    weight: 19.5,
    height: 0.9,
    file_name: "./images/pokemons/063.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "064",
    zukan_sub_id: 0,
    name: "勇基拉",
    pokemon_sub_name: "",
    weight: 56.5,
    height: 1.3,
    file_name: "./images/pokemons/064.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "065",
    zukan_sub_id: 0,
    name: "胡地",
    pokemon_sub_name: "",
    weight: 48,
    height: 1.5,
    file_name: "./images/pokemons/065.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "065",
    zukan_sub_id: 1,
    name: "超級胡地",
    pokemon_sub_name: "",
    weight: 48,
    height: 1.2,
    file_name: "./images/pokemons/065-1.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "066",
    zukan_sub_id: 0,
    name: "腕力",
    pokemon_sub_name: "",
    weight: 19.5,
    height: 0.8,
    file_name: "./images/pokemons/066.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "067",
    zukan_sub_id: 0,
    name: "豪力",
    pokemon_sub_name: "",
    weight: 70.5,
    height: 1.5,
    file_name: "./images/pokemons/067.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "068",
    zukan_sub_id: 0,
    name: "怪力",
    pokemon_sub_name: "",
    weight: 130,
    height: 1.6,
    file_name: "./images/pokemons/068.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "069",
    zukan_sub_id: 0,
    name: "喇叭芽",
    pokemon_sub_name: "",
    weight: 4,
    height: 0.7,
    file_name: "./images/pokemons/069.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "070",
    zukan_sub_id: 0,
    name: "口呆花",
    pokemon_sub_name: "",
    weight: 6.4,
    height: 1,
    file_name: "./images/pokemons/070.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "071",
    zukan_sub_id: 0,
    name: "大食花",
    pokemon_sub_name: "",
    weight: 15.5,
    height: 1.7,
    file_name: "./images/pokemons/071.png",
    pokemon_type_id: "grass,poison",
    pokemon_type_name: "草,毒",
  },
  {
    id: "072",
    zukan_sub_id: 0,
    name: "瑪瑙水母",
    pokemon_sub_name: "",
    weight: 45.5,
    height: 0.9,
    file_name: "./images/pokemons/072.png",
    pokemon_type_id: "water,poison",
    pokemon_type_name: "水,毒",
  },
  {
    id: "073",
    zukan_sub_id: 0,
    name: "毒刺水母",
    pokemon_sub_name: "",
    weight: 55,
    height: 1.6,
    file_name: "./images/pokemons/073.png",
    pokemon_type_id: "water,poison",
    pokemon_type_name: "水,毒",
  },
  {
    id: "074",
    zukan_sub_id: 0,
    name: "小拳石",
    pokemon_sub_name: "",
    weight: 20,
    height: 0.4,
    file_name: "./images/pokemons/074.png",
    pokemon_type_id: "rock,ground",
    pokemon_type_name: "岩石,地面",
  },
  {
    id: "074",
    zukan_sub_id: 1,
    name: "小拳石",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 20.3,
    height: 0.4,
    file_name: "./images/pokemons/074-1.png",
    pokemon_type_id: "rock,electric",
    pokemon_type_name: "岩石,電",
  },
  {
    id: "075",
    zukan_sub_id: 0,
    name: "隆隆石",
    pokemon_sub_name: "",
    weight: 105,
    height: 1,
    file_name: "./images/pokemons/075.png",
    pokemon_type_id: "rock,ground",
    pokemon_type_name: "岩石,地面",
  },
  {
    id: "075",
    zukan_sub_id: 1,
    name: "隆隆石",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 110,
    height: 1,
    file_name: "./images/pokemons/075-1.png",
    pokemon_type_id: "rock,electric",
    pokemon_type_name: "岩石,電",
  },
  {
    id: "076",
    zukan_sub_id: 0,
    name: "隆隆岩",
    pokemon_sub_name: "",
    weight: 300,
    height: 1.4,
    file_name: "./images/pokemons/076.png",
    pokemon_type_id: "rock,ground",
    pokemon_type_name: "岩石,地面",
  },
  {
    id: "076",
    zukan_sub_id: 1,
    name: "隆隆岩",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 316,
    height: 1.7,
    file_name: "./images/pokemons/076-1.png",
    pokemon_type_id: "rock,electric",
    pokemon_type_name: "岩石,電",
  },
  {
    id: "077",
    zukan_sub_id: 0,
    name: "小火馬",
    pokemon_sub_name: "",
    weight: 30,
    height: 1,
    file_name: "./images/pokemons/077.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "078",
    zukan_sub_id: 0,
    name: "烈焰馬",
    pokemon_sub_name: "",
    weight: 95,
    height: 1.7,
    file_name: "./images/pokemons/078.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "079",
    zukan_sub_id: 0,
    name: "呆呆獸",
    pokemon_sub_name: "",
    weight: 36,
    height: 1.2,
    file_name: "./images/pokemons/079.png",
    pokemon_type_id: "water,psychic",
    pokemon_type_name: "水,超能力",
  },
  {
    id: "080",
    zukan_sub_id: 0,
    name: "呆殼獸",
    pokemon_sub_name: "",
    weight: 78.5,
    height: 1.6,
    file_name: "./images/pokemons/080.png",
    pokemon_type_id: "water,psychic",
    pokemon_type_name: "水,超能力",
  },
  {
    id: "080",
    zukan_sub_id: 1,
    name: "超級呆殼獸",
    pokemon_sub_name: "",
    weight: 120,
    height: 2,
    file_name: "./images/pokemons/080-1.png",
    pokemon_type_id: "water,psychic",
    pokemon_type_name: "水,超能力",
  },
  {
    id: "081",
    zukan_sub_id: 0,
    name: "小磁怪",
    pokemon_sub_name: "",
    weight: 6,
    height: 0.3,
    file_name: "./images/pokemons/081.png",
    pokemon_type_id: "electric,steel",
    pokemon_type_name: "電,鋼",
  },
  {
    id: "082",
    zukan_sub_id: 0,
    name: "三合一磁怪",
    pokemon_sub_name: "",
    weight: 60,
    height: 1,
    file_name: "./images/pokemons/082.png",
    pokemon_type_id: "electric,steel",
    pokemon_type_name: "電,鋼",
  },
  {
    id: "083",
    zukan_sub_id: 0,
    name: "大蔥鴨",
    pokemon_sub_name: "",
    weight: 15,
    height: 0.8,
    file_name: "./images/pokemons/083.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "084",
    zukan_sub_id: 0,
    name: "嘟嘟",
    pokemon_sub_name: "",
    weight: 39.2,
    height: 1.4,
    file_name: "./images/pokemons/084.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "085",
    zukan_sub_id: 0,
    name: "嘟嘟利",
    pokemon_sub_name: "",
    weight: 85.2,
    height: 1.8,
    file_name: "./images/pokemons/085.png",
    pokemon_type_id: "normal,flying",
    pokemon_type_name: "一般,飛行",
  },
  {
    id: "086",
    zukan_sub_id: 0,
    name: "小海獅",
    pokemon_sub_name: "",
    weight: 90,
    height: 1.1,
    file_name: "./images/pokemons/086.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "087",
    zukan_sub_id: 0,
    name: "白海獅",
    pokemon_sub_name: "",
    weight: 120,
    height: 1.7,
    file_name: "./images/pokemons/087.png",
    pokemon_type_id: "water,ice",
    pokemon_type_name: "水,冰",
  },
  {
    id: "088",
    zukan_sub_id: 0,
    name: "臭泥",
    pokemon_sub_name: "",
    weight: 30,
    height: 0.9,
    file_name: "./images/pokemons/088.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "088",
    zukan_sub_id: 1,
    name: "臭泥",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 42,
    height: 0.7,
    file_name: "./images/pokemons/088-1.png",
    pokemon_type_id: "poison,dark",
    pokemon_type_name: "毒,惡",
  },
  {
    id: "089",
    zukan_sub_id: 0,
    name: "臭臭泥",
    pokemon_sub_name: "",
    weight: 30,
    height: 1.2,
    file_name: "./images/pokemons/089.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "089",
    zukan_sub_id: 1,
    name: "臭臭泥",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 52,
    height: 1,
    file_name: "./images/pokemons/089-1.png",
    pokemon_type_id: "poison,dark",
    pokemon_type_name: "毒,惡",
  },
  {
    id: "090",
    zukan_sub_id: 0,
    name: "大舌貝",
    pokemon_sub_name: "",
    weight: 4,
    height: 0.3,
    file_name: "./images/pokemons/090.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "091",
    zukan_sub_id: 0,
    name: "刺甲貝",
    pokemon_sub_name: "",
    weight: 132.5,
    height: 1.5,
    file_name: "./images/pokemons/091.png",
    pokemon_type_id: "water,ice",
    pokemon_type_name: "水,冰",
  },
  {
    id: "092",
    zukan_sub_id: 0,
    name: "鬼斯",
    pokemon_sub_name: "",
    weight: 0.1,
    height: 1.3,
    file_name: "./images/pokemons/092.png",
    pokemon_type_id: "ghost,poison",
    pokemon_type_name: "幽靈,毒",
  },
  {
    id: "093",
    zukan_sub_id: 0,
    name: "鬼斯通",
    pokemon_sub_name: "",
    weight: 0.1,
    height: 1.6,
    file_name: "./images/pokemons/093.png",
    pokemon_type_id: "ghost,poison",
    pokemon_type_name: "幽靈,毒",
  },
  {
    id: "094",
    zukan_sub_id: 0,
    name: "耿鬼",
    pokemon_sub_name: "",
    weight: 40.5,
    height: 1.5,
    file_name: "./images/pokemons/094.png",
    pokemon_type_id: "ghost,poison",
    pokemon_type_name: "幽靈,毒",
  },
  {
    id: "094",
    zukan_sub_id: 1,
    name: "超級耿鬼",
    pokemon_sub_name: "",
    weight: 40.5,
    height: 1.4,
    file_name: "./images/pokemons/094-1.png",
    pokemon_type_id: "ghost,poison",
    pokemon_type_name: "幽靈,毒",
  },
  {
    id: "095",
    zukan_sub_id: 0,
    name: "大岩蛇",
    pokemon_sub_name: "",
    weight: 210,
    height: 8.8,
    file_name: "./images/pokemons/095.png",
    pokemon_type_id: "rock,ground",
    pokemon_type_name: "岩石,地面",
  },
  {
    id: "096",
    zukan_sub_id: 0,
    name: "催眠貘",
    pokemon_sub_name: "",
    weight: 32.4,
    height: 1,
    file_name: "./images/pokemons/096.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "097",
    zukan_sub_id: 0,
    name: "引夢貘人",
    pokemon_sub_name: "",
    weight: 75.6,
    height: 1.6,
    file_name: "./images/pokemons/097.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "098",
    zukan_sub_id: 0,
    name: "大鉗蟹",
    pokemon_sub_name: "",
    weight: 6.5,
    height: 0.4,
    file_name: "./images/pokemons/098.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "099",
    zukan_sub_id: 0,
    name: "巨鉗蟹",
    pokemon_sub_name: "",
    weight: 60,
    height: 1.3,
    file_name: "./images/pokemons/099.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "100",
    zukan_sub_id: 0,
    name: "霹靂電球",
    pokemon_sub_name: "",
    weight: 10.4,
    height: 0.5,
    file_name: "./images/pokemons/100.png",
    pokemon_type_id: "electric",
    pokemon_type_name: "電",
  },
  {
    id: "101",
    zukan_sub_id: 0,
    name: "頑皮雷彈",
    pokemon_sub_name: "",
    weight: 66.6,
    height: 1.2,
    file_name: "./images/pokemons/101.png",
    pokemon_type_id: "electric",
    pokemon_type_name: "電",
  },
  {
    id: "102",
    zukan_sub_id: 0,
    name: "蛋蛋",
    pokemon_sub_name: "",
    weight: 2.5,
    height: 0.4,
    file_name: "./images/pokemons/102.png",
    pokemon_type_id: "grass,psychic",
    pokemon_type_name: "草,超能力",
  },
  {
    id: "103",
    zukan_sub_id: 0,
    name: "椰蛋樹",
    pokemon_sub_name: "",
    weight: 120,
    height: 2,
    file_name: "./images/pokemons/103.png",
    pokemon_type_id: "grass,psychic",
    pokemon_type_name: "草,超能力",
  },
  {
    id: "103",
    zukan_sub_id: 1,
    name: "椰蛋樹",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 415.6,
    height: 10.9,
    file_name: "./images/pokemons/103-1.png",
    pokemon_type_id: "grass,dragon",
    pokemon_type_name: "草,龍",
  },
  {
    id: "104",
    zukan_sub_id: 0,
    name: "卡拉卡拉",
    pokemon_sub_name: "",
    weight: 6.5,
    height: 0.4,
    file_name: "./images/pokemons/104.png",
    pokemon_type_id: "ground",
    pokemon_type_name: "地面",
  },
  {
    id: "105",
    zukan_sub_id: 0,
    name: "嘎啦嘎啦",
    pokemon_sub_name: "",
    weight: 45,
    height: 1,
    file_name: "./images/pokemons/105.png",
    pokemon_type_id: "ground",
    pokemon_type_name: "地面",
  },
  {
    id: "105",
    zukan_sub_id: 1,
    name: "嘎啦嘎啦",
    pokemon_sub_name: "阿羅拉的樣子",
    weight: 34,
    height: 1,
    file_name: "./images/pokemons/105-1.png",
    pokemon_type_id: "fire,ghost",
    pokemon_type_name: "火,幽靈",
  },
  {
    id: "106",
    zukan_sub_id: 0,
    name: "飛腿郎",
    pokemon_sub_name: "",
    weight: 49.8,
    height: 1.5,
    file_name: "./images/pokemons/106.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "107",
    zukan_sub_id: 0,
    name: "快拳郎",
    pokemon_sub_name: "",
    weight: 50.2,
    height: 1.4,
    file_name: "./images/pokemons/107.png",
    pokemon_type_id: "fighting",
    pokemon_type_name: "格鬥",
  },
  {
    id: "108",
    zukan_sub_id: 0,
    name: "大舌頭",
    pokemon_sub_name: "",
    weight: 65.5,
    height: 1.2,
    file_name: "./images/pokemons/108.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "109",
    zukan_sub_id: 0,
    name: "瓦斯彈",
    pokemon_sub_name: "",
    weight: 1,
    height: 0.6,
    file_name: "./images/pokemons/109.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "110",
    zukan_sub_id: 0,
    name: "雙彈瓦斯",
    pokemon_sub_name: "",
    weight: 9.5,
    height: 1.2,
    file_name: "./images/pokemons/110.png",
    pokemon_type_id: "poison",
    pokemon_type_name: "毒",
  },
  {
    id: "111",
    zukan_sub_id: 0,
    name: "獨角犀牛",
    pokemon_sub_name: "",
    weight: 115,
    height: 1,
    file_name: "./images/pokemons/111.png",
    pokemon_type_id: "ground,rock",
    pokemon_type_name: "地面,岩石",
  },
  {
    id: "112",
    zukan_sub_id: 0,
    name: "鑽角犀獸",
    pokemon_sub_name: "",
    weight: 120,
    height: 1.9,
    file_name: "./images/pokemons/112.png",
    pokemon_type_id: "ground,rock",
    pokemon_type_name: "地面,岩石",
  },
  {
    id: "113",
    zukan_sub_id: 0,
    name: "吉利蛋",
    pokemon_sub_name: "",
    weight: 34.6,
    height: 1.1,
    file_name: "./images/pokemons/113.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "114",
    zukan_sub_id: 0,
    name: "蔓藤怪",
    pokemon_sub_name: "",
    weight: 35,
    height: 1,
    file_name: "./images/pokemons/114.png",
    pokemon_type_id: "grass",
    pokemon_type_name: "草",
  },
  {
    id: "115",
    zukan_sub_id: 0,
    name: "袋獸",
    pokemon_sub_name: "",
    weight: 80,
    height: 2.2,
    file_name: "./images/pokemons/115.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "115",
    zukan_sub_id: 1,
    name: "超級袋獸",
    pokemon_sub_name: "",
    weight: 100,
    height: 2.2,
    file_name: "./images/pokemons/115-1.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "116",
    zukan_sub_id: 0,
    name: "墨海馬",
    pokemon_sub_name: "",
    weight: 8,
    height: 0.4,
    file_name: "./images/pokemons/116.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "117",
    zukan_sub_id: 0,
    name: "海刺龍",
    pokemon_sub_name: "",
    weight: 25,
    height: 1.2,
    file_name: "./images/pokemons/117.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "118",
    zukan_sub_id: 0,
    name: "角金魚",
    pokemon_sub_name: "",
    weight: 15,
    height: 0.6,
    file_name: "./images/pokemons/118.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "119",
    zukan_sub_id: 0,
    name: "金魚王",
    pokemon_sub_name: "",
    weight: 39,
    height: 1.3,
    file_name: "./images/pokemons/119.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "120",
    zukan_sub_id: 0,
    name: "海星星",
    pokemon_sub_name: "",
    weight: 34.5,
    height: 0.8,
    file_name: "./images/pokemons/120.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "121",
    zukan_sub_id: 0,
    name: "寶石海星",
    pokemon_sub_name: "",
    weight: 80,
    height: 1.1,
    file_name: "./images/pokemons/121.png",
    pokemon_type_id: "water,psychic",
    pokemon_type_name: "水,超能力",
  },
  {
    id: "122",
    zukan_sub_id: 0,
    name: "魔牆人偶",
    pokemon_sub_name: "",
    weight: 54.5,
    height: 1.3,
    file_name: "./images/pokemons/122.png",
    pokemon_type_id: "psychic,fairy",
    pokemon_type_name: "超能力,妖精",
  },
  {
    id: "123",
    zukan_sub_id: 0,
    name: "飛天螳螂",
    pokemon_sub_name: "",
    weight: 56,
    height: 1.5,
    file_name: "./images/pokemons/123.png",
    pokemon_type_id: "bug,flying",
    pokemon_type_name: "蟲,飛行",
  },
  {
    id: "124",
    zukan_sub_id: 0,
    name: "迷唇姐",
    pokemon_sub_name: "",
    weight: 40.6,
    height: 1.4,
    file_name: "./images/pokemons/124.png",
    pokemon_type_id: "ice,psychic",
    pokemon_type_name: "冰,超能力",
  },
  {
    id: "125",
    zukan_sub_id: 0,
    name: "電擊獸",
    pokemon_sub_name: "",
    weight: 30,
    height: 1.1,
    file_name: "./images/pokemons/125.png",
    pokemon_type_id: "electric",
    pokemon_type_name: "電",
  },
  {
    id: "126",
    zukan_sub_id: 0,
    name: "鴨嘴火獸",
    pokemon_sub_name: "",
    weight: 44.5,
    height: 1.3,
    file_name: "./images/pokemons/126.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "127",
    zukan_sub_id: 0,
    name: "凱羅斯",
    pokemon_sub_name: "",
    weight: 55,
    height: 1.5,
    file_name: "./images/pokemons/127.png",
    pokemon_type_id: "bug",
    pokemon_type_name: "蟲",
  },
  {
    id: "127",
    zukan_sub_id: 1,
    name: "超級凱羅斯",
    pokemon_sub_name: "",
    weight: 59,
    height: 1.7,
    file_name: "./images/pokemons/127-1.png",
    pokemon_type_id: "bug,flying",
    pokemon_type_name: "蟲,飛行",
  },
  {
    id: "128",
    zukan_sub_id: 0,
    name: "肯泰羅",
    pokemon_sub_name: "",
    weight: 88.4,
    height: 1.4,
    file_name: "./images/pokemons/128.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "129",
    zukan_sub_id: 0,
    name: "鯉魚王",
    pokemon_sub_name: "",
    weight: 10,
    height: 0.9,
    file_name: "./images/pokemons/129.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "130",
    zukan_sub_id: 0,
    name: "暴鯉龍",
    pokemon_sub_name: "",
    weight: 235,
    height: 6.5,
    file_name: "./images/pokemons/130.png",
    pokemon_type_id: "water,flying",
    pokemon_type_name: "水,飛行",
  },
  {
    id: "130",
    zukan_sub_id: 1,
    name: "超級暴鯉龍",
    pokemon_sub_name: "",
    weight: 305,
    height: 6.5,
    file_name: "./images/pokemons/130-1.png",
    pokemon_type_id: "water,dark",
    pokemon_type_name: "水,惡",
  },
  {
    id: "131",
    zukan_sub_id: 0,
    name: "拉普拉斯",
    pokemon_sub_name: "",
    weight: 220,
    height: 2.5,
    file_name: "./images/pokemons/131.png",
    pokemon_type_id: "water,ice",
    pokemon_type_name: "水,冰",
  },
  {
    id: "132",
    zukan_sub_id: 0,
    name: "百變怪",
    pokemon_sub_name: "",
    weight: 4,
    height: 0.3,
    file_name: "./images/pokemons/132.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "133",
    zukan_sub_id: 0,
    name: "伊布",
    pokemon_sub_name: "",
    weight: 6.5,
    height: 0.3,
    file_name: "./images/pokemons/133.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "134",
    zukan_sub_id: 0,
    name: "水伊布",
    pokemon_sub_name: "",
    weight: 29,
    height: 1,
    file_name: "./images/pokemons/134.png",
    pokemon_type_id: "water",
    pokemon_type_name: "水",
  },
  {
    id: "135",
    zukan_sub_id: 0,
    name: "雷伊布",
    pokemon_sub_name: "",
    weight: 24.5,
    height: 0.8,
    file_name: "./images/pokemons/135.png",
    pokemon_type_id: "electric",
    pokemon_type_name: "電",
  },
  {
    id: "136",
    zukan_sub_id: 0,
    name: "火伊布",
    pokemon_sub_name: "",
    weight: 25,
    height: 0.9,
    file_name: "./images/pokemons/136.png",
    pokemon_type_id: "fire",
    pokemon_type_name: "火",
  },
  {
    id: "137",
    zukan_sub_id: 0,
    name: "多邊獸",
    pokemon_sub_name: "",
    weight: 36.5,
    height: 0.8,
    file_name: "./images/pokemons/137.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "138",
    zukan_sub_id: 0,
    name: "菊石獸",
    pokemon_sub_name: "",
    weight: 7.5,
    height: 0.4,
    file_name: "./images/pokemons/138.png",
    pokemon_type_id: "rock,water",
    pokemon_type_name: "岩石,水",
  },
  {
    id: "139",
    zukan_sub_id: 0,
    name: "多刺菊石獸",
    pokemon_sub_name: "",
    weight: 35,
    height: 1,
    file_name: "./images/pokemons/139.png",
    pokemon_type_id: "rock,water",
    pokemon_type_name: "岩石,水",
  },
  {
    id: "140",
    zukan_sub_id: 0,
    name: "化石盔",
    pokemon_sub_name: "",
    weight: 11.5,
    height: 0.5,
    file_name: "./images/pokemons/140.png",
    pokemon_type_id: "rock,water",
    pokemon_type_name: "岩石,水",
  },
  {
    id: "141",
    zukan_sub_id: 0,
    name: "鐮刀盔",
    pokemon_sub_name: "",
    weight: 40.5,
    height: 1.3,
    file_name: "./images/pokemons/141.png",
    pokemon_type_id: "rock,water",
    pokemon_type_name: "岩石,水",
  },
  {
    id: "142",
    zukan_sub_id: 0,
    name: "化石翼龍",
    pokemon_sub_name: "",
    weight: 59,
    height: 1.8,
    file_name: "./images/pokemons/142.png",
    pokemon_type_id: "rock,flying",
    pokemon_type_name: "岩石,飛行",
  },
  {
    id: "142",
    zukan_sub_id: 1,
    name: "超級化石翼龍",
    pokemon_sub_name: "",
    weight: 79,
    height: 2.1,
    file_name: "./images/pokemons/142-1.png",
    pokemon_type_id: "rock,flying",
    pokemon_type_name: "岩石,飛行",
  },
  {
    id: "143",
    zukan_sub_id: 0,
    name: "卡比獸",
    pokemon_sub_name: "",
    weight: 460,
    height: 2.1,
    file_name: "./images/pokemons/143.png",
    pokemon_type_id: "normal",
    pokemon_type_name: "一般",
  },
  {
    id: "144",
    zukan_sub_id: 0,
    name: "急凍鳥",
    pokemon_sub_name: "",
    weight: 55.4,
    height: 1.7,
    file_name: "./images/pokemons/144.png",
    pokemon_type_id: "ice,flying",
    pokemon_type_name: "冰,飛行",
  },
  {
    id: "145",
    zukan_sub_id: 0,
    name: "閃電鳥",
    pokemon_sub_name: "",
    weight: 52.6,
    height: 1.6,
    file_name: "./images/pokemons/145.png",
    pokemon_type_id: "electric,flying",
    pokemon_type_name: "電,飛行",
  },
  {
    id: "146",
    zukan_sub_id: 0,
    name: "火焰鳥",
    pokemon_sub_name: "",
    weight: 60,
    height: 2,
    file_name: "./images/pokemons/146.png",
    pokemon_type_id: "fire,flying",
    pokemon_type_name: "火,飛行",
  },
  {
    id: "147",
    zukan_sub_id: 0,
    name: "迷你龍",
    pokemon_sub_name: "",
    weight: 3.3,
    height: 1.8,
    file_name: "./images/pokemons/147.png",
    pokemon_type_id: "dragon",
    pokemon_type_name: "龍",
  },
  {
    id: "148",
    zukan_sub_id: 0,
    name: "哈克龍",
    pokemon_sub_name: "",
    weight: 16.5,
    height: 4,
    file_name: "./images/pokemons/148.png",
    pokemon_type_id: "dragon",
    pokemon_type_name: "龍",
  },
  {
    id: "149",
    zukan_sub_id: 0,
    name: "快龍",
    pokemon_sub_name: "",
    weight: 210,
    height: 2.2,
    file_name: "./images/pokemons/149.png",
    pokemon_type_id: "dragon,flying",
    pokemon_type_name: "龍,飛行",
  },
  {
    id: "150",
    zukan_sub_id: 0,
    name: "超夢",
    pokemon_sub_name: "",
    weight: 122,
    height: 2,
    file_name: "./images/pokemons/150.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "150",
    zukan_sub_id: 1,
    name: "超級超夢Ｘ",
    pokemon_sub_name: "",
    weight: 127,
    height: 2.3,
    file_name: "./images/pokemons/150-1.png",
    pokemon_type_id: "psychic,fighting",
    pokemon_type_name: "超能力,格鬥",
  },
  {
    id: "150",
    zukan_sub_id: 2,
    name: "超級超夢Ｙ",
    pokemon_sub_name: "",
    weight: 33,
    height: 1.5,
    file_name: "./images/pokemons/150-2.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
  {
    id: "151",
    zukan_sub_id: 0,
    name: "夢幻",
    pokemon_sub_name: "",
    weight: 4,
    height: 0.4,
    file_name: "./images/pokemons/151.png",
    pokemon_type_id: "psychic",
    pokemon_type_name: "超能力",
  },
];

export default {
  data,
};
