/**
 * 資料來源:https://tw.portal-pokemon.com
 */
let data = [
    {
        "id": "001",
        "zukan_sub_id": 0,
        "name": "妙蛙種子",
        "pokemon_sub_name": "",
        "weight": 6.9,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1JvabIxVsBNFz5ut_jEtPN6vBgqbg8NQS",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "002",
        "zukan_sub_id": 0,
        "name": "妙蛙草",
        "pokemon_sub_name": "",
        "weight": 13,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1qwFNg3aiGF3OCQxW2PKYSg1zLtz9sLoc",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "003",
        "zukan_sub_id": 0,
        "name": "妙蛙花",
        "pokemon_sub_name": "",
        "weight": 100,
        "height": 2,
        "file_name": "https://drive.google.com/uc?export=view&id=1juaxZF0TCKPaYdSGmNSslOYRdgy-XTjk",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "003",
        "zukan_sub_id": 1,
        "name": "超級妙蛙花",
        "pokemon_sub_name": "",
        "weight": 155.5,
        "height": 2.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1fnakn4W87dySn8BbVDoP_daqY79AA-1j",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "004",
        "zukan_sub_id": 0,
        "name": "小火龍",
        "pokemon_sub_name": "",
        "weight": 8.5,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1IiLn68GjM4UZeF-YhfAzyMVnZj1Z7Ub7",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "005",
        "zukan_sub_id": 0,
        "name": "火恐龍",
        "pokemon_sub_name": "",
        "weight": 19,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1QX0RA30rkOUBvi-K6hIZ2xXW4O5yqQj_",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "006",
        "zukan_sub_id": 0,
        "name": "噴火龍",
        "pokemon_sub_name": "",
        "weight": 90.5,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1_fjI1g81TA2zUkOFnjAfAahay6m3uGhf",
        "pokemon_type_id": "fire,flying",
        "pokemon_type_name": "火,飛行"
    },
    {
        "id": "006",
        "zukan_sub_id": 1,
        "name": "超級噴火龍Ｘ",
        "pokemon_sub_name": "",
        "weight": 110.5,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1Ox8cTD8STWqVAJy_q9xAXYYUXULSjAsQ",
        "pokemon_type_id": "fire,dragon",
        "pokemon_type_name": "火,龍"
    },
    {
        "id": "006",
        "zukan_sub_id": 2,
        "name": "超級噴火龍Ｙ",
        "pokemon_sub_name": "",
        "weight": 100.5,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1hTtk9XHKMrP34jtKQ34fpYO6IfLAd5vi",
        "pokemon_type_id": "fire,flying",
        "pokemon_type_name": "火,飛行"
    },
    {
        "id": "007",
        "zukan_sub_id": 0,
        "name": "傑尼龜",
        "pokemon_sub_name": "",
        "weight": 9,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1SYQToA7rrsDM1FHEiX16l_DIV0R8ZY43",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "008",
        "zukan_sub_id": 0,
        "name": "卡咪龜",
        "pokemon_sub_name": "",
        "weight": 22.5,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=15O69sYjxPkWk2-FYj-H0gwsKEXS2PrQg",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "009",
        "zukan_sub_id": 0,
        "name": "水箭龜",
        "pokemon_sub_name": "",
        "weight": 85.5,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=199XtAEK8gBEnvpPzN-h8A4nvv-i1bkr4",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "009",
        "zukan_sub_id": 1,
        "name": "超級水箭龜",
        "pokemon_sub_name": "",
        "weight": 101.1,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1dZ0PhvsuAbGXoxiNt881pU8Wq6NN6kl7",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "010",
        "zukan_sub_id": 0,
        "name": "綠毛蟲",
        "pokemon_sub_name": "",
        "weight": 2.9,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1EXCd4FnOqhbIhpSekOIondGHu7MZquRQ",
        "pokemon_type_id": "bug",
        "pokemon_type_name": "蟲"
    },
    {
        "id": "011",
        "zukan_sub_id": 0,
        "name": "鐵甲蛹",
        "pokemon_sub_name": "",
        "weight": 9.9,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1A41Q8TiKPM8z4WIOhiOjR2l1S7wL-T7E",
        "pokemon_type_id": "bug",
        "pokemon_type_name": "蟲"
    },
    {
        "id": "012",
        "zukan_sub_id": 0,
        "name": "巴大蝶",
        "pokemon_sub_name": "",
        "weight": 32,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1OZXnEQWqOUHSdnyG6SJ4ZYDxJAKGEDi3",
        "pokemon_type_id": "bug,flying",
        "pokemon_type_name": "蟲,飛行"
    },
    {
        "id": "013",
        "zukan_sub_id": 0,
        "name": "獨角蟲",
        "pokemon_sub_name": "",
        "weight": 3.2,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1kaRFQLJBPmSJxczaIbvcN423FMOuwwr0",
        "pokemon_type_id": "bug,poison",
        "pokemon_type_name": "蟲,毒"
    },
    {
        "id": "014",
        "zukan_sub_id": 0,
        "name": "鐵殼蛹",
        "pokemon_sub_name": "",
        "weight": 10,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1Iigph3p2fWQuyRIHQUUOJ0VY9MBswwGD",
        "pokemon_type_id": "bug,poison",
        "pokemon_type_name": "蟲,毒"
    },
    {
        "id": "015",
        "zukan_sub_id": 0,
        "name": "大針蜂",
        "pokemon_sub_name": "",
        "weight": 29.5,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1FCh5NGlZtZjOpKeRkRbpFBAJdxs6xBil",
        "pokemon_type_id": "bug,poison",
        "pokemon_type_name": "蟲,毒"
    },
    {
        "id": "015",
        "zukan_sub_id": 1,
        "name": "超級大針蜂",
        "pokemon_sub_name": "",
        "weight": 40.5,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1l-NuqxESC0IAmOk0dKKQDg72jH6Rb8eh",
        "pokemon_type_id": "bug,poison",
        "pokemon_type_name": "蟲,毒"
    },
    {
        "id": "016",
        "zukan_sub_id": 0,
        "name": "波波",
        "pokemon_sub_name": "",
        "weight": 1.8,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1wtz-l8OICAgFTTYbSdu7SW-JNxDl1aCd",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "017",
        "zukan_sub_id": 0,
        "name": "比比鳥",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=10_E5kBoE2I4pOP3yUfdqt_S44p2iqpxG",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "018",
        "zukan_sub_id": 0,
        "name": "大比鳥",
        "pokemon_sub_name": "",
        "weight": 39.5,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1W_L9GBXa-2bCV1vSGhWD4z0L4uhETyT-",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "018",
        "zukan_sub_id": 1,
        "name": "超級大比鳥",
        "pokemon_sub_name": "",
        "weight": 50.5,
        "height": 2.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1iIBGv9z_OxcfEZymRBsAmxh-5jaBof_R",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "019",
        "zukan_sub_id": 0,
        "name": "小拉達",
        "pokemon_sub_name": "",
        "weight": 3.5,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1wPdxbjhucgeroH6P7SbbshxJ6mIgu9L2",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "019",
        "zukan_sub_id": 1,
        "name": "小拉達",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 3.8,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1TrsTpvuqzXwF3lUr1tvSuMcu3hEMQOmS",
        "pokemon_type_id": "dark,normal",
        "pokemon_type_name": "惡,一般"
    },
    {
        "id": "020",
        "zukan_sub_id": 0,
        "name": "拉達",
        "pokemon_sub_name": "",
        "weight": 18.5,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1cfK3iIDCP75zaop6YIxAsOvygOhRX2Lb",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "020",
        "zukan_sub_id": 1,
        "name": "拉達",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 25.5,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1QwdTHndeCD-3JKD1NKEWpLirofzKeCMZ",
        "pokemon_type_id": "dark,normal",
        "pokemon_type_name": "惡,一般"
    },
    {
        "id": "021",
        "zukan_sub_id": 0,
        "name": "烈雀",
        "pokemon_sub_name": "",
        "weight": 2,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1cw6_3WbwkYcwjNEhZxIot9WkEYX8pcbY",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "022",
        "zukan_sub_id": 0,
        "name": "大嘴雀",
        "pokemon_sub_name": "",
        "weight": 38,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1UAVsLkAythGDtEJQBkR-bs5PwCkdGKC7",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "023",
        "zukan_sub_id": 0,
        "name": "阿柏蛇",
        "pokemon_sub_name": "",
        "weight": 6.9,
        "height": 2,
        "file_name": "https://drive.google.com/uc?export=view&id=1GUEYef7gceQGmVvlr482e4JUsZGzxVYp",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "024",
        "zukan_sub_id": 0,
        "name": "阿柏怪",
        "pokemon_sub_name": "",
        "weight": 65,
        "height": 3.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1hVJc37bUymlB7_7ZK-nSvtXyka-fzBiu",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "025",
        "zukan_sub_id": 0,
        "name": "皮卡丘",
        "pokemon_sub_name": "",
        "weight": 6,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=192elOJ4oPKu-zeP8Sayq1t6Vv5JGMgcB",
        "pokemon_type_id": "electric",
        "pokemon_type_name": "電"
    },
    {
        "id": "026",
        "zukan_sub_id": 0,
        "name": "雷丘",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1N7H5d7yUxoopWngF3iyiLMlKfg4VL7ge",
        "pokemon_type_id": "electric",
        "pokemon_type_name": "電"
    },
    {
        "id": "026",
        "zukan_sub_id": 1,
        "name": "雷丘",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 21,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1DwzWoxLLggw3xjd-sbgBcCWnMqxiU7rY",
        "pokemon_type_id": "electric,psychic",
        "pokemon_type_name": "電,超能力"
    },
    {
        "id": "027",
        "zukan_sub_id": 0,
        "name": "穿山鼠",
        "pokemon_sub_name": "",
        "weight": 12,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1vxhQkdj3wCVkHImM0C2O_XsCP6qIGA19",
        "pokemon_type_id": "ground",
        "pokemon_type_name": "地面"
    },
    {
        "id": "027",
        "zukan_sub_id": 1,
        "name": "穿山鼠",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 40,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=10vSElL1JfVmpgrWX_vsKRFFjWsshKw55",
        "pokemon_type_id": "ice,steel",
        "pokemon_type_name": "冰,鋼"
    },
    {
        "id": "028",
        "zukan_sub_id": 0,
        "name": "穿山王",
        "pokemon_sub_name": "",
        "weight": 29.5,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1sI3WpiXLgLS_CPlyd_DERwFTf4nNQQR0",
        "pokemon_type_id": "ground",
        "pokemon_type_name": "地面"
    },
    {
        "id": "028",
        "zukan_sub_id": 1,
        "name": "穿山王",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 55,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1ZLcAEGjmw5w2hMMONZuR8isw1btfifrB",
        "pokemon_type_id": "ice,steel",
        "pokemon_type_name": "冰,鋼"
    },
    {
        "id": "029",
        "zukan_sub_id": 0,
        "name": "尼多蘭",
        "pokemon_sub_name": "",
        "weight": 7,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1ozsFplZsjeS7r3DMrclVwEzSN_AW-2ta",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "030",
        "zukan_sub_id": 0,
        "name": "尼多娜",
        "pokemon_sub_name": "",
        "weight": 20,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=14xu-KPIKGDBokPMqz_ieIXR0wV2GOJ6Z",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "031",
        "zukan_sub_id": 0,
        "name": "尼多后",
        "pokemon_sub_name": "",
        "weight": 60,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1imoV7mk8IecWU4TK-DJNTIpoK_wub7E-",
        "pokemon_type_id": "poison,ground",
        "pokemon_type_name": "毒,地面"
    },
    {
        "id": "032",
        "zukan_sub_id": 0,
        "name": "尼多朗",
        "pokemon_sub_name": "",
        "weight": 9,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=10AnoyjiFuPleYUyvlYh3qYUL_GF3KXPJ",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "033",
        "zukan_sub_id": 0,
        "name": "尼多力諾",
        "pokemon_sub_name": "",
        "weight": 19.5,
        "height": 0.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1I9KJaxwmN7v9vviqtS8nJ8dWGSkBIrL2",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "034",
        "zukan_sub_id": 0,
        "name": "尼多王",
        "pokemon_sub_name": "",
        "weight": 62,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=12PU5-ChNXOaPSGSAsHvGgRTuOHea2mcv",
        "pokemon_type_id": "poison,ground",
        "pokemon_type_name": "毒,地面"
    },
    {
        "id": "035",
        "zukan_sub_id": 0,
        "name": "皮皮",
        "pokemon_sub_name": "",
        "weight": 7.5,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1x8pPUZd8ETUe5_6_QnbaEhefkRiNtidI",
        "pokemon_type_id": "fairy",
        "pokemon_type_name": "妖精"
    },
    {
        "id": "036",
        "zukan_sub_id": 0,
        "name": "皮可西",
        "pokemon_sub_name": "",
        "weight": 40,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1P7aYV9muloQAh9GD6CNbwvcp_-EGCes4",
        "pokemon_type_id": "fairy",
        "pokemon_type_name": "妖精"
    },
    {
        "id": "037",
        "zukan_sub_id": 0,
        "name": "六尾",
        "pokemon_sub_name": "",
        "weight": 9.9,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1PNM0ODkLfmaE5DwWtH0p8WcBZI2-VS2u",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "037",
        "zukan_sub_id": 1,
        "name": "六尾",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 9.9,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1kOGjRRZCKKaXM--VOnd-qo7iyeJkhpEp",
        "pokemon_type_id": "ice",
        "pokemon_type_name": "冰"
    },
    {
        "id": "038",
        "zukan_sub_id": 0,
        "name": "九尾",
        "pokemon_sub_name": "",
        "weight": 19.9,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1ZkN7QwRnSNlSkYKaiS0mSx6mJnI5wTxL",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "038",
        "zukan_sub_id": 1,
        "name": "九尾",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 19.9,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1xol90d1jgdprfYuiGSpl_ws3FwE7aFLQ",
        "pokemon_type_id": "ice,fairy",
        "pokemon_type_name": "冰,妖精"
    },
    {
        "id": "039",
        "zukan_sub_id": 0,
        "name": "胖丁",
        "pokemon_sub_name": "",
        "weight": 5.5,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1N4NzLZh6LPk4oOuCX5Gfd0VbITTQVCWL",
        "pokemon_type_id": "normal,fairy",
        "pokemon_type_name": "一般,妖精"
    },
    {
        "id": "040",
        "zukan_sub_id": 0,
        "name": "胖可丁",
        "pokemon_sub_name": "",
        "weight": 12,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1cs7zFPy_3L5XB2tu8qJn2PLRvdXCnc0-",
        "pokemon_type_id": "normal,fairy",
        "pokemon_type_name": "一般,妖精"
    },
    {
        "id": "041",
        "zukan_sub_id": 0,
        "name": "超音蝠",
        "pokemon_sub_name": "",
        "weight": 7.5,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1BccsdlHBApAYISYWyaogicFHe5kf4UvN",
        "pokemon_type_id": "poison,flying",
        "pokemon_type_name": "毒,飛行"
    },
    {
        "id": "042",
        "zukan_sub_id": 0,
        "name": "大嘴蝠",
        "pokemon_sub_name": "",
        "weight": 55,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1VJLlACuwdnKn9ywhYQrJLIb2NLYqyNUc",
        "pokemon_type_id": "poison,flying",
        "pokemon_type_name": "毒,飛行"
    },
    {
        "id": "043",
        "zukan_sub_id": 0,
        "name": "走路草",
        "pokemon_sub_name": "",
        "weight": 5.4,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1B7DZe38Eh3XLsMmMKngAXAw4AFzt5ZKb",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "044",
        "zukan_sub_id": 0,
        "name": "臭臭花",
        "pokemon_sub_name": "",
        "weight": 8.6,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1yKXXgWgGgoNZauG1MYjk3Hst7sLsK4_Q",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "045",
        "zukan_sub_id": 0,
        "name": "霸王花",
        "pokemon_sub_name": "",
        "weight": 18.6,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1V7x7i-7ogrK318BZjxgBxI6v75YOEjgf",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "046",
        "zukan_sub_id": 0,
        "name": "派拉斯",
        "pokemon_sub_name": "",
        "weight": 5.4,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1dvh3OsuzmJBUHVAKeWRfRACRYv2dI2iE",
        "pokemon_type_id": "bug,grass",
        "pokemon_type_name": "蟲,草"
    },
    {
        "id": "047",
        "zukan_sub_id": 0,
        "name": "派拉斯特",
        "pokemon_sub_name": "",
        "weight": 29.5,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1RUvYK_Am8ScUVDk0PshWwIIO9k4g2Eyk",
        "pokemon_type_id": "bug,grass",
        "pokemon_type_name": "蟲,草"
    },
    {
        "id": "048",
        "zukan_sub_id": 0,
        "name": "毛球",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1pMJ2B9tYwNwd1oPWDeSasvJmDze1ammp",
        "pokemon_type_id": "bug,poison",
        "pokemon_type_name": "蟲,毒"
    },
    {
        "id": "049",
        "zukan_sub_id": 0,
        "name": "摩魯蛾",
        "pokemon_sub_name": "",
        "weight": 12.5,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1xy37F8vj-F9__st7BjPvvfnFoPzCoQoY",
        "pokemon_type_id": "bug,poison",
        "pokemon_type_name": "蟲,毒"
    },
    {
        "id": "050",
        "zukan_sub_id": 0,
        "name": "地鼠",
        "pokemon_sub_name": "",
        "weight": 0.8,
        "height": 0.2,
        "file_name": "https://drive.google.com/uc?export=view&id=13upUIUqILPTVWox7PHs-56kqmNTm0xmJ",
        "pokemon_type_id": "ground",
        "pokemon_type_name": "地面"
    },
    {
        "id": "050",
        "zukan_sub_id": 1,
        "name": "地鼠",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 1,
        "height": 0.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1EN4Kc3nwkpsp1TphnV30K03q78CLuMqZ",
        "pokemon_type_id": "ground,steel",
        "pokemon_type_name": "地面,鋼"
    },
    {
        "id": "051",
        "zukan_sub_id": 0,
        "name": "三地鼠",
        "pokemon_sub_name": "",
        "weight": 33.3,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1f-u7k-yj_ffamfBT75sPxgUv0W7UHulA",
        "pokemon_type_id": "ground",
        "pokemon_type_name": "地面"
    },
    {
        "id": "051",
        "zukan_sub_id": 1,
        "name": "三地鼠",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 66.6,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1ZAqwdEKlG2qfqEa_JOqCn8Zaafdn2_PR",
        "pokemon_type_id": "ground,steel",
        "pokemon_type_name": "地面,鋼"
    },
    {
        "id": "052",
        "zukan_sub_id": 0,
        "name": "喵喵",
        "pokemon_sub_name": "",
        "weight": 4.2,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1rEq2rHfDFbUJ18PGQRBQ9ZO8K-l6ckxV",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "052",
        "zukan_sub_id": 1,
        "name": "喵喵",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 4.2,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1a88WE9NMqckwfgvD3zrnfJjzONB_wS18",
        "pokemon_type_id": "dark",
        "pokemon_type_name": "惡"
    },
    {
        "id": "053",
        "zukan_sub_id": 0,
        "name": "貓老大",
        "pokemon_sub_name": "",
        "weight": 32,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1MdiSQBbxdIB1bbf3jUC-aYaanwL7qLn7",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "053",
        "zukan_sub_id": 1,
        "name": "貓老大",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 33,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1l-PZiaweQct5SarqQzr8QElEKlEohVZP",
        "pokemon_type_id": "dark",
        "pokemon_type_name": "惡"
    },
    {
        "id": "054",
        "zukan_sub_id": 0,
        "name": "可達鴨",
        "pokemon_sub_name": "",
        "weight": 19.6,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1b0hpZffcw0xa1Qbh-78Z1WYK2rpvRoQJ",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "055",
        "zukan_sub_id": 0,
        "name": "哥達鴨",
        "pokemon_sub_name": "",
        "weight": 76.6,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1DdeTvsciNCc-7u0xZGnFo-5gK1a1XvN4",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "056",
        "zukan_sub_id": 0,
        "name": "猴怪",
        "pokemon_sub_name": "",
        "weight": 28,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1SMZb5TPLoaVsygaaFEZohe2AyZzYq7Eh",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "057",
        "zukan_sub_id": 0,
        "name": "火爆猴",
        "pokemon_sub_name": "",
        "weight": 32,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1wKfwIy579sBUb6Ut5-cZb8fIusX82CDZ",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "058",
        "zukan_sub_id": 0,
        "name": "卡蒂狗",
        "pokemon_sub_name": "",
        "weight": 19,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1_XWcSVxPyMImZNEEnSahY_knSTzBULER",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "059",
        "zukan_sub_id": 0,
        "name": "風速狗",
        "pokemon_sub_name": "",
        "weight": 155,
        "height": 1.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1tQ2ScJj9HsHKTh5j8hC5sBMa8XFZFe1c",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "060",
        "zukan_sub_id": 0,
        "name": "蚊香蝌蚪",
        "pokemon_sub_name": "",
        "weight": 12.4,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1weT1vp9qR_mKrhEObal1tfRPTZi6Kc77",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "061",
        "zukan_sub_id": 0,
        "name": "蚊香君",
        "pokemon_sub_name": "",
        "weight": 20,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1rPD2LI5SGFUMhrDql9GuynjPWBvNSEEf",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "062",
        "zukan_sub_id": 0,
        "name": "蚊香泳士",
        "pokemon_sub_name": "",
        "weight": 54,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1qFrfdSm48JYFBlGSSvS32xQJJ3n9Wv0S",
        "pokemon_type_id": "water,fighting",
        "pokemon_type_name": "水,格鬥"
    },
    {
        "id": "063",
        "zukan_sub_id": 0,
        "name": "凱西",
        "pokemon_sub_name": "",
        "weight": 19.5,
        "height": 0.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1FQ2pCbCxw4JwKbnowU19REPm5XVTP8lP",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "064",
        "zukan_sub_id": 0,
        "name": "勇基拉",
        "pokemon_sub_name": "",
        "weight": 56.5,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=19mSj73QuSHaHIGQHJ3GmOgIGbkTAkm8G",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "065",
        "zukan_sub_id": 0,
        "name": "胡地",
        "pokemon_sub_name": "",
        "weight": 48,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1kUBD8PYqRSwl-IgF96zAfVtZStqvARek",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "065",
        "zukan_sub_id": 1,
        "name": "超級胡地",
        "pokemon_sub_name": "",
        "weight": 48,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1Z6IZ06PbDzaM1J1OQQVg-_qNI-QQYxAd",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "066",
        "zukan_sub_id": 0,
        "name": "腕力",
        "pokemon_sub_name": "",
        "weight": 19.5,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1lXOXVm-2fE77sGit6CU6VGqhI1p8Ypmk",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "067",
        "zukan_sub_id": 0,
        "name": "豪力",
        "pokemon_sub_name": "",
        "weight": 70.5,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1gR9VgJ9W24RY8orQ3nj_I1X3zJ4w__B1",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "068",
        "zukan_sub_id": 0,
        "name": "怪力",
        "pokemon_sub_name": "",
        "weight": 130,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1okq_O3jhvGsRzcUaLwTd2Q_uSNYIONC_",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "069",
        "zukan_sub_id": 0,
        "name": "喇叭芽",
        "pokemon_sub_name": "",
        "weight": 4,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1AuIbsGPV8OEz-hdk7GPIFu1iMoHcpoyQ",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "070",
        "zukan_sub_id": 0,
        "name": "口呆花",
        "pokemon_sub_name": "",
        "weight": 6.4,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1TpA6hxszNqvxWrxxCJBlWYX_8iVoqq2u",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "071",
        "zukan_sub_id": 0,
        "name": "大食花",
        "pokemon_sub_name": "",
        "weight": 15.5,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1DK7mnLrzbUpZ84yXekZ6_gZEn3HPxfdV",
        "pokemon_type_id": "grass,poison",
        "pokemon_type_name": "草,毒"
    },
    {
        "id": "072",
        "zukan_sub_id": 0,
        "name": "瑪瑙水母",
        "pokemon_sub_name": "",
        "weight": 45.5,
        "height": 0.9,
        "file_name": "https://drive.google.com/uc?export=view&id=10iwvzHw9MfWLl7YB-HFidLdlBI8zea-H",
        "pokemon_type_id": "water,poison",
        "pokemon_type_name": "水,毒"
    },
    {
        "id": "073",
        "zukan_sub_id": 0,
        "name": "毒刺水母",
        "pokemon_sub_name": "",
        "weight": 55,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=16LYDz9LnjivV7iMjJsMfKEMY_mSpT4Zg",
        "pokemon_type_id": "water,poison",
        "pokemon_type_name": "水,毒"
    },
    {
        "id": "074",
        "zukan_sub_id": 0,
        "name": "小拳石",
        "pokemon_sub_name": "",
        "weight": 20,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=189ym0dWeLSt6b6_GF5KVzUOVTiCbbgQN",
        "pokemon_type_id": "rock,ground",
        "pokemon_type_name": "岩石,地面"
    },
    {
        "id": "074",
        "zukan_sub_id": 1,
        "name": "小拳石",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 20.3,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1UxiVOXnyX1J98LNTKjv9ZEuXBFrzMXxD",
        "pokemon_type_id": "rock,electric",
        "pokemon_type_name": "岩石,電"
    },
    {
        "id": "075",
        "zukan_sub_id": 0,
        "name": "隆隆石",
        "pokemon_sub_name": "",
        "weight": 105,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1hmM1WbChQdfJuloHaSY3WsceoFGGLC6-",
        "pokemon_type_id": "rock,ground",
        "pokemon_type_name": "岩石,地面"
    },
    {
        "id": "075",
        "zukan_sub_id": 1,
        "name": "隆隆石",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 110,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1iWAhKf-9butD5LHiqtq2P8gL3vhZJq3B",
        "pokemon_type_id": "rock,electric",
        "pokemon_type_name": "岩石,電"
    },
    {
        "id": "076",
        "zukan_sub_id": 0,
        "name": "隆隆岩",
        "pokemon_sub_name": "",
        "weight": 300,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1cBORoFWNcTVdr0vjn4yvwVtO1ju6os1F",
        "pokemon_type_id": "rock,ground",
        "pokemon_type_name": "岩石,地面"
    },
    {
        "id": "076",
        "zukan_sub_id": 1,
        "name": "隆隆岩",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 316,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1TIBaRV2ZyDxPrMrVBfjqQA3aKZ_pHQXM",
        "pokemon_type_id": "rock,electric",
        "pokemon_type_name": "岩石,電"
    },
    {
        "id": "077",
        "zukan_sub_id": 0,
        "name": "小火馬",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1vfCAwArOaChJRkLSPFl-Z6ryfDl368N0",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "078",
        "zukan_sub_id": 0,
        "name": "烈焰馬",
        "pokemon_sub_name": "",
        "weight": 95,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1BUSeLZNyCcltw4Om2PCfr01tw41V6kPW",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "079",
        "zukan_sub_id": 0,
        "name": "呆呆獸",
        "pokemon_sub_name": "",
        "weight": 36,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1jbhFBTnKHs7dUP_y99yG4FKhImPp6ifJ",
        "pokemon_type_id": "water,psychic",
        "pokemon_type_name": "水,超能力"
    },
    {
        "id": "080",
        "zukan_sub_id": 0,
        "name": "呆殼獸",
        "pokemon_sub_name": "",
        "weight": 78.5,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1cV9AkwnQlo9x0SOqDXFWAqrPftTUfV17",
        "pokemon_type_id": "water,psychic",
        "pokemon_type_name": "水,超能力"
    },
    {
        "id": "080",
        "zukan_sub_id": 1,
        "name": "超級呆殼獸",
        "pokemon_sub_name": "",
        "weight": 120,
        "height": 2,
        "file_name": "https://drive.google.com/uc?export=view&id=1uTs0BGRWJiGW3qhUS9hnWuVGDaKOqkD7",
        "pokemon_type_id": "water,psychic",
        "pokemon_type_name": "水,超能力"
    },
    {
        "id": "081",
        "zukan_sub_id": 0,
        "name": "小磁怪",
        "pokemon_sub_name": "",
        "weight": 6,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1JhaskluB2lboF57NtOFSCrZK9JZAvoe5",
        "pokemon_type_id": "electric,steel",
        "pokemon_type_name": "電,鋼"
    },
    {
        "id": "082",
        "zukan_sub_id": 0,
        "name": "三合一磁怪",
        "pokemon_sub_name": "",
        "weight": 60,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1_k_IWUsYzoZqFIt-qUpKAdLHgEgRy8_p",
        "pokemon_type_id": "electric,steel",
        "pokemon_type_name": "電,鋼"
    },
    {
        "id": "083",
        "zukan_sub_id": 0,
        "name": "大蔥鴨",
        "pokemon_sub_name": "",
        "weight": 15,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1xKfRx5eVKRCkH4VYGzqYl9rMqDtZqEEO",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "084",
        "zukan_sub_id": 0,
        "name": "嘟嘟",
        "pokemon_sub_name": "",
        "weight": 39.2,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1Lq3eUPBLoPoK60YV8qyt7mG7C9IXdUHj",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "085",
        "zukan_sub_id": 0,
        "name": "嘟嘟利",
        "pokemon_sub_name": "",
        "weight": 85.2,
        "height": 1.8,
        "file_name": "https://drive.google.com/uc?export=view&id=17SFPSuMT_ZWRWWZ2HvYCo6x6gqaxNBeP",
        "pokemon_type_id": "normal,flying",
        "pokemon_type_name": "一般,飛行"
    },
    {
        "id": "086",
        "zukan_sub_id": 0,
        "name": "小海獅",
        "pokemon_sub_name": "",
        "weight": 90,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1X176dJ9cn9mbimO8duaGbsJ8vt1DM7RD",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "087",
        "zukan_sub_id": 0,
        "name": "白海獅",
        "pokemon_sub_name": "",
        "weight": 120,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1YKsVzH6iaFjmDa7P_-HnFNoA3nlRbNYH",
        "pokemon_type_id": "water,ice",
        "pokemon_type_name": "水,冰"
    },
    {
        "id": "088",
        "zukan_sub_id": 0,
        "name": "臭泥",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 0.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1oXTygrtR1pt12RXoE8DpmUowCqd7vZRt",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "088",
        "zukan_sub_id": 1,
        "name": "臭泥",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 42,
        "height": 0.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1zeLpSHrgoQCxxCk6pWZ9VdNMmk4mwOjp",
        "pokemon_type_id": "poison,dark",
        "pokemon_type_name": "毒,惡"
    },
    {
        "id": "089",
        "zukan_sub_id": 0,
        "name": "臭臭泥",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1G-ZRDVb6jSDa0_ouQVvRMj8kf-zc48FY",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "089",
        "zukan_sub_id": 1,
        "name": "臭臭泥",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 52,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1fL8GsK-3RkLXgXej3gYIY3xHDfLwr67W",
        "pokemon_type_id": "poison,dark",
        "pokemon_type_name": "毒,惡"
    },
    {
        "id": "090",
        "zukan_sub_id": 0,
        "name": "大舌貝",
        "pokemon_sub_name": "",
        "weight": 4,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1UDj5vi4MvkT4YphPiLsfhgSqLSMdOhHG",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "091",
        "zukan_sub_id": 0,
        "name": "刺甲貝",
        "pokemon_sub_name": "",
        "weight": 132.5,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1pTkTrheiDyZovLJqSW96kBB1CbGhgeKk",
        "pokemon_type_id": "water,ice",
        "pokemon_type_name": "水,冰"
    },
    {
        "id": "092",
        "zukan_sub_id": 0,
        "name": "鬼斯",
        "pokemon_sub_name": "",
        "weight": 0.1,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1sI7HWh2QdhcQXOrn0eZkmUhD8A4tqmX5",
        "pokemon_type_id": "ghost,poison",
        "pokemon_type_name": "幽靈,毒"
    },
    {
        "id": "093",
        "zukan_sub_id": 0,
        "name": "鬼斯通",
        "pokemon_sub_name": "",
        "weight": 0.1,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1wHKW3lLNJDMA30QWloypw8dEI19gYdXY",
        "pokemon_type_id": "ghost,poison",
        "pokemon_type_name": "幽靈,毒"
    },
    {
        "id": "094",
        "zukan_sub_id": 0,
        "name": "耿鬼",
        "pokemon_sub_name": "",
        "weight": 40.5,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1BunfIusMOQt22ZH00SCBPRBEQqjssIxn",
        "pokemon_type_id": "ghost,poison",
        "pokemon_type_name": "幽靈,毒"
    },
    {
        "id": "094",
        "zukan_sub_id": 1,
        "name": "超級耿鬼",
        "pokemon_sub_name": "",
        "weight": 40.5,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1UezLhVZyQP42Y6DvToZMiqZJvBqKOxk2",
        "pokemon_type_id": "ghost,poison",
        "pokemon_type_name": "幽靈,毒"
    },
    {
        "id": "095",
        "zukan_sub_id": 0,
        "name": "大岩蛇",
        "pokemon_sub_name": "",
        "weight": 210,
        "height": 8.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1w9Pp3n84fCIg5tC5g5yobmcK3CBOjipV",
        "pokemon_type_id": "rock,ground",
        "pokemon_type_name": "岩石,地面"
    },
    {
        "id": "096",
        "zukan_sub_id": 0,
        "name": "催眠貘",
        "pokemon_sub_name": "",
        "weight": 32.4,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1fU8MrbFFxhXVvF1_5ZuCyEZRX23EjXix",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "097",
        "zukan_sub_id": 0,
        "name": "引夢貘人",
        "pokemon_sub_name": "",
        "weight": 75.6,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1HDVEQuRzDsJv4tOJo4ewjE1X0nRSEv12",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "098",
        "zukan_sub_id": 0,
        "name": "大鉗蟹",
        "pokemon_sub_name": "",
        "weight": 6.5,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1hXqlt0J2gGkpEDzwWlyOekoztAQXDQx9",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "099",
        "zukan_sub_id": 0,
        "name": "巨鉗蟹",
        "pokemon_sub_name": "",
        "weight": 60,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1QgbgNH1h_E0zdl9kk_kLlqiNvkSlEqWL",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "100",
        "zukan_sub_id": 0,
        "name": "霹靂電球",
        "pokemon_sub_name": "",
        "weight": 10.4,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=19-HZwYKj9IGqM56xP2UwytAb1blh3iow",
        "pokemon_type_id": "electric",
        "pokemon_type_name": "電"
    },
    {
        "id": "101",
        "zukan_sub_id": 0,
        "name": "頑皮雷彈",
        "pokemon_sub_name": "",
        "weight": 66.6,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=10v9Ua9rAHP9Epp8155i4L09GaGGrbm9l",
        "pokemon_type_id": "electric",
        "pokemon_type_name": "電"
    },
    {
        "id": "102",
        "zukan_sub_id": 0,
        "name": "蛋蛋",
        "pokemon_sub_name": "",
        "weight": 2.5,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1WLsGbs7uTBYrFeemI7K6Ci5-Sqc-Pq-a",
        "pokemon_type_id": "grass,psychic",
        "pokemon_type_name": "草,超能力"
    },
    {
        "id": "103",
        "zukan_sub_id": 0,
        "name": "椰蛋樹",
        "pokemon_sub_name": "",
        "weight": 120,
        "height": 2,
        "file_name": "https://drive.google.com/uc?export=view&id=1eDgRYKGyAo2iZeZzfRGqOweYfFUOzYeY",
        "pokemon_type_id": "grass,psychic",
        "pokemon_type_name": "草,超能力"
    },
    {
        "id": "103",
        "zukan_sub_id": 1,
        "name": "椰蛋樹",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 415.6,
        "height": 10.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1qSqGr0obaWpQgXtik92Yfy2z8d_whHIg",
        "pokemon_type_id": "grass,dragon",
        "pokemon_type_name": "草,龍"
    },
    {
        "id": "104",
        "zukan_sub_id": 0,
        "name": "卡拉卡拉",
        "pokemon_sub_name": "",
        "weight": 6.5,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1g_Oq9FS1ZrkfFDRFckqS-UU36ttmgauD",
        "pokemon_type_id": "ground",
        "pokemon_type_name": "地面"
    },
    {
        "id": "105",
        "zukan_sub_id": 0,
        "name": "嘎啦嘎啦",
        "pokemon_sub_name": "",
        "weight": 45,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=10DM5RJLcFkjqjPqd_iWTXirDXfov3cYR",
        "pokemon_type_id": "ground",
        "pokemon_type_name": "地面"
    },
    {
        "id": "105",
        "zukan_sub_id": 1,
        "name": "嘎啦嘎啦",
        "pokemon_sub_name": "阿羅拉的樣子",
        "weight": 34,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=16_TItbZVBAo0XCs6ohqq3-NHkM87-OH0",
        "pokemon_type_id": "fire,ghost",
        "pokemon_type_name": "火,幽靈"
    },
    {
        "id": "106",
        "zukan_sub_id": 0,
        "name": "飛腿郎",
        "pokemon_sub_name": "",
        "weight": 49.8,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1v3VG2IYnkOjsK24ihJvZs7KsEQKl7sSC",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "107",
        "zukan_sub_id": 0,
        "name": "快拳郎",
        "pokemon_sub_name": "",
        "weight": 50.2,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1OM6_zPtGClrXjuMMscaJ6L9nBprBkJKF",
        "pokemon_type_id": "fighting",
        "pokemon_type_name": "格鬥"
    },
    {
        "id": "108",
        "zukan_sub_id": 0,
        "name": "大舌頭",
        "pokemon_sub_name": "",
        "weight": 65.5,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1bAZvaLt8OznkGy-GwVkJJiuhAFfMB3_j",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "109",
        "zukan_sub_id": 0,
        "name": "瓦斯彈",
        "pokemon_sub_name": "",
        "weight": 1,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1-g4pzqGzGgOIINGFO4Q9l-W6LoMTwd0D",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "110",
        "zukan_sub_id": 0,
        "name": "雙彈瓦斯",
        "pokemon_sub_name": "",
        "weight": 9.5,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=16YVHL0HDLDirISvGRmbEl1FUtUW96-n3",
        "pokemon_type_id": "poison",
        "pokemon_type_name": "毒"
    },
    {
        "id": "111",
        "zukan_sub_id": 0,
        "name": "獨角犀牛",
        "pokemon_sub_name": "",
        "weight": 115,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1RjPbXTf2m6uCPEt613DEEf4RyttWwCR1",
        "pokemon_type_id": "ground,rock",
        "pokemon_type_name": "地面,岩石"
    },
    {
        "id": "112",
        "zukan_sub_id": 0,
        "name": "鑽角犀獸",
        "pokemon_sub_name": "",
        "weight": 120,
        "height": 1.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1xH_mOpiEC3vFw7u50GCiMdyUoRgzYJQr",
        "pokemon_type_id": "ground,rock",
        "pokemon_type_name": "地面,岩石"
    },
    {
        "id": "113",
        "zukan_sub_id": 0,
        "name": "吉利蛋",
        "pokemon_sub_name": "",
        "weight": 34.6,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1voe4xyciTt42dFoB1LiKO-169EkJ9BNQ",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "114",
        "zukan_sub_id": 0,
        "name": "蔓藤怪",
        "pokemon_sub_name": "",
        "weight": 35,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1ynThCCuqy5hEF2odfI6HJUbPL_4gN5g8",
        "pokemon_type_id": "grass",
        "pokemon_type_name": "草"
    },
    {
        "id": "115",
        "zukan_sub_id": 0,
        "name": "袋獸",
        "pokemon_sub_name": "",
        "weight": 80,
        "height": 2.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1G44UMzmWLUzhkLwAe1Aj5BWiQ8XXVVwN",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "115",
        "zukan_sub_id": 1,
        "name": "超級袋獸",
        "pokemon_sub_name": "",
        "weight": 100,
        "height": 2.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1-9GMk9jnVKMt9GcymOSpi5QNKFT8DtC2",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "116",
        "zukan_sub_id": 0,
        "name": "墨海馬",
        "pokemon_sub_name": "",
        "weight": 8,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1lF6eDqhhfKVc4CoYlHQfvPKijApdYDbR",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "117",
        "zukan_sub_id": 0,
        "name": "海刺龍",
        "pokemon_sub_name": "",
        "weight": 25,
        "height": 1.2,
        "file_name": "https://drive.google.com/uc?export=view&id=16CHDz4i6cJGq-UESFmubv68UyJVGu1G2",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "118",
        "zukan_sub_id": 0,
        "name": "角金魚",
        "pokemon_sub_name": "",
        "weight": 15,
        "height": 0.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1YRfs9VW-xvuYE0Cy_PEVW558cBPqtteF",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "119",
        "zukan_sub_id": 0,
        "name": "金魚王",
        "pokemon_sub_name": "",
        "weight": 39,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1MeqvbPXYeOB6iF3hWOsY259PyysO-7VJ",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "120",
        "zukan_sub_id": 0,
        "name": "海星星",
        "pokemon_sub_name": "",
        "weight": 34.5,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=11eSPWJ_08yA5BPdfWzN5F2rF5ayPpBii",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "121",
        "zukan_sub_id": 0,
        "name": "寶石海星",
        "pokemon_sub_name": "",
        "weight": 80,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1ZSUOf-5QXg9O7AAsAjcy3F9kjvOydz23",
        "pokemon_type_id": "water,psychic",
        "pokemon_type_name": "水,超能力"
    },
    {
        "id": "122",
        "zukan_sub_id": 0,
        "name": "魔牆人偶",
        "pokemon_sub_name": "",
        "weight": 54.5,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=19LLEs0shaoK5dV2-fwtg3XaC0MkNblwA",
        "pokemon_type_id": "psychic,fairy",
        "pokemon_type_name": "超能力,妖精"
    },
    {
        "id": "123",
        "zukan_sub_id": 0,
        "name": "飛天螳螂",
        "pokemon_sub_name": "",
        "weight": 56,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1ryBFOOoC4yQjYeNhthRmpKc_laKQe6HP",
        "pokemon_type_id": "bug,flying",
        "pokemon_type_name": "蟲,飛行"
    },
    {
        "id": "124",
        "zukan_sub_id": 0,
        "name": "迷唇姐",
        "pokemon_sub_name": "",
        "weight": 40.6,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1BvTWaGRv2SCXkTERYya2_-3vmpl78T7a",
        "pokemon_type_id": "ice,psychic",
        "pokemon_type_name": "冰,超能力"
    },
    {
        "id": "125",
        "zukan_sub_id": 0,
        "name": "電擊獸",
        "pokemon_sub_name": "",
        "weight": 30,
        "height": 1.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1QdGTHulMnxeGM2rJzxWOqxQnm5OmD-aW",
        "pokemon_type_id": "electric",
        "pokemon_type_name": "電"
    },
    {
        "id": "126",
        "zukan_sub_id": 0,
        "name": "鴨嘴火獸",
        "pokemon_sub_name": "",
        "weight": 44.5,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1V0Eust7B3kv3azrbl5_GYnKl51foKqi2",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "127",
        "zukan_sub_id": 0,
        "name": "凱羅斯",
        "pokemon_sub_name": "",
        "weight": 55,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1EDXR1v2GnLOdlPesOjxHcIXSev5dQZKX",
        "pokemon_type_id": "bug",
        "pokemon_type_name": "蟲"
    },
    {
        "id": "127",
        "zukan_sub_id": 1,
        "name": "超級凱羅斯",
        "pokemon_sub_name": "",
        "weight": 59,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=1PPQ3gQJeCI6wPQ-JHKZftPlYrV5DYZFd",
        "pokemon_type_id": "bug,flying",
        "pokemon_type_name": "蟲,飛行"
    },
    {
        "id": "128",
        "zukan_sub_id": 0,
        "name": "肯泰羅",
        "pokemon_sub_name": "",
        "weight": 88.4,
        "height": 1.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1vpmrZm7Rj6eoYujoD6enETv4ua-gYP3K",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "129",
        "zukan_sub_id": 0,
        "name": "鯉魚王",
        "pokemon_sub_name": "",
        "weight": 10,
        "height": 0.9,
        "file_name": "https://drive.google.com/uc?export=view&id=19u-nEKkommBCPJKWL60x513Uis7fJJyl",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "130",
        "zukan_sub_id": 0,
        "name": "暴鯉龍",
        "pokemon_sub_name": "",
        "weight": 235,
        "height": 6.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1B0HFbQZSMZZf-mUGRaIA0W3jP-XGUaON",
        "pokemon_type_id": "water,flying",
        "pokemon_type_name": "水,飛行"
    },
    {
        "id": "130",
        "zukan_sub_id": 1,
        "name": "超級暴鯉龍",
        "pokemon_sub_name": "",
        "weight": 305,
        "height": 6.5,
        "file_name": "https://drive.google.com/uc?export=view&id=11HosSeP8a2hMrKJTobK0G3WlD7V1QbnZ",
        "pokemon_type_id": "water,dark",
        "pokemon_type_name": "水,惡"
    },
    {
        "id": "131",
        "zukan_sub_id": 0,
        "name": "拉普拉斯",
        "pokemon_sub_name": "",
        "weight": 220,
        "height": 2.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1c0KktDX5EbW00fNd4E7sTGTJYi0yxPB_",
        "pokemon_type_id": "water,ice",
        "pokemon_type_name": "水,冰"
    },
    {
        "id": "132",
        "zukan_sub_id": 0,
        "name": "百變怪",
        "pokemon_sub_name": "",
        "weight": 4,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1AkiTPWUbDevWeQzvMVg4E3j0eWU9YA2d",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "133",
        "zukan_sub_id": 0,
        "name": "伊布",
        "pokemon_sub_name": "",
        "weight": 6.5,
        "height": 0.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1VQsXXB8cYz6oPFAinx9Z9DpkFhcln1r8",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "134",
        "zukan_sub_id": 0,
        "name": "水伊布",
        "pokemon_sub_name": "",
        "weight": 29,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=19pjp_ri7cNAT7SIkb6q8Sds4Pzez2_Tr",
        "pokemon_type_id": "water",
        "pokemon_type_name": "水"
    },
    {
        "id": "135",
        "zukan_sub_id": 0,
        "name": "雷伊布",
        "pokemon_sub_name": "",
        "weight": 24.5,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=12LurrIUYK9Eyys6TIhVEnXMgXQB63zXN",
        "pokemon_type_id": "electric",
        "pokemon_type_name": "電"
    },
    {
        "id": "136",
        "zukan_sub_id": 0,
        "name": "火伊布",
        "pokemon_sub_name": "",
        "weight": 25,
        "height": 0.9,
        "file_name": "https://drive.google.com/uc?export=view&id=1VhwwV7304krf8ddheNYjENTc8Q8YeP6r",
        "pokemon_type_id": "fire",
        "pokemon_type_name": "火"
    },
    {
        "id": "137",
        "zukan_sub_id": 0,
        "name": "多邊獸",
        "pokemon_sub_name": "",
        "weight": 36.5,
        "height": 0.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1kNBPArrwNOHPUKFQXE751emDu85BhPvT",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "138",
        "zukan_sub_id": 0,
        "name": "菊石獸",
        "pokemon_sub_name": "",
        "weight": 7.5,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1lDE0pvwLlpNxtfZViDrQMhY7ACjCwTXW",
        "pokemon_type_id": "rock,water",
        "pokemon_type_name": "岩石,水"
    },
    {
        "id": "139",
        "zukan_sub_id": 0,
        "name": "多刺菊石獸",
        "pokemon_sub_name": "",
        "weight": 35,
        "height": 1,
        "file_name": "https://drive.google.com/uc?export=view&id=1SjxLLnDNo2AgVf0IFJ7K1NTm3iCSVvpB",
        "pokemon_type_id": "rock,water",
        "pokemon_type_name": "岩石,水"
    },
    {
        "id": "140",
        "zukan_sub_id": 0,
        "name": "化石盔",
        "pokemon_sub_name": "",
        "weight": 11.5,
        "height": 0.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1_Dpvh2TTkOz_GBmxMEfAs15jjRCfjM54",
        "pokemon_type_id": "rock,water",
        "pokemon_type_name": "岩石,水"
    },
    {
        "id": "141",
        "zukan_sub_id": 0,
        "name": "鐮刀盔",
        "pokemon_sub_name": "",
        "weight": 40.5,
        "height": 1.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1sd3L3tEjgD3aNjzoC9tOuJghJYE7_Or6",
        "pokemon_type_id": "rock,water",
        "pokemon_type_name": "岩石,水"
    },
    {
        "id": "142",
        "zukan_sub_id": 0,
        "name": "化石翼龍",
        "pokemon_sub_name": "",
        "weight": 59,
        "height": 1.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1C9SNTybeHRlNCrn8m4lQzzqdSxxd-6zX",
        "pokemon_type_id": "rock,flying",
        "pokemon_type_name": "岩石,飛行"
    },
    {
        "id": "142",
        "zukan_sub_id": 1,
        "name": "超級化石翼龍",
        "pokemon_sub_name": "",
        "weight": 79,
        "height": 2.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1Fg9dN5tKrptfrQK1VG3ASXmnuP26AOmf",
        "pokemon_type_id": "rock,flying",
        "pokemon_type_name": "岩石,飛行"
    },
    {
        "id": "143",
        "zukan_sub_id": 0,
        "name": "卡比獸",
        "pokemon_sub_name": "",
        "weight": 460,
        "height": 2.1,
        "file_name": "https://drive.google.com/uc?export=view&id=1Q-VV8sRtEuCCo3D1DXBgjzOSti9h5Zha",
        "pokemon_type_id": "normal",
        "pokemon_type_name": "一般"
    },
    {
        "id": "144",
        "zukan_sub_id": 0,
        "name": "急凍鳥",
        "pokemon_sub_name": "",
        "weight": 55.4,
        "height": 1.7,
        "file_name": "https://drive.google.com/uc?export=view&id=13VAosAp1HD5YfPnUMTsIIFjNbUD3MnEt",
        "pokemon_type_id": "ice,flying",
        "pokemon_type_name": "冰,飛行"
    },
    {
        "id": "145",
        "zukan_sub_id": 0,
        "name": "閃電鳥",
        "pokemon_sub_name": "",
        "weight": 52.6,
        "height": 1.6,
        "file_name": "https://drive.google.com/uc?export=view&id=1GFy9-L4XkomAUrhCYGLjNFwS9sVD4v-A",
        "pokemon_type_id": "electric,flying",
        "pokemon_type_name": "電,飛行"
    },
    {
        "id": "146",
        "zukan_sub_id": 0,
        "name": "火焰鳥",
        "pokemon_sub_name": "",
        "weight": 60,
        "height": 2,
        "file_name": "https://drive.google.com/uc?export=view&id=1jkOzOt7I92Jm1vGPply99ib3gioN2UDn",
        "pokemon_type_id": "fire,flying",
        "pokemon_type_name": "火,飛行"
    },
    {
        "id": "147",
        "zukan_sub_id": 0,
        "name": "迷你龍",
        "pokemon_sub_name": "",
        "weight": 3.3,
        "height": 1.8,
        "file_name": "https://drive.google.com/uc?export=view&id=1guBVUW5sLdou-ZWw2ni-72jMX-u1raZp",
        "pokemon_type_id": "dragon",
        "pokemon_type_name": "龍"
    },
    {
        "id": "148",
        "zukan_sub_id": 0,
        "name": "哈克龍",
        "pokemon_sub_name": "",
        "weight": 16.5,
        "height": 4,
        "file_name": "https://drive.google.com/uc?export=view&id=1drlgY1MaGiGOI2nFaThDvQKWM4ky1lZs",
        "pokemon_type_id": "dragon",
        "pokemon_type_name": "龍"
    },
    {
        "id": "149",
        "zukan_sub_id": 0,
        "name": "快龍",
        "pokemon_sub_name": "",
        "weight": 210,
        "height": 2.2,
        "file_name": "https://drive.google.com/uc?export=view&id=1siMChYOqCYKy1cO7nzPs7FmUY3pDGjhX",
        "pokemon_type_id": "dragon,flying",
        "pokemon_type_name": "龍,飛行"
    },
    {
        "id": "150",
        "zukan_sub_id": 0,
        "name": "超夢",
        "pokemon_sub_name": "",
        "weight": 122,
        "height": 2,
        "file_name": "https://drive.google.com/uc?export=view&id=1D6ASDj43p2HXR-PuLqpI3da7IN-nTInH",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "150",
        "zukan_sub_id": 1,
        "name": "超級超夢Ｘ",
        "pokemon_sub_name": "",
        "weight": 127,
        "height": 2.3,
        "file_name": "https://drive.google.com/uc?export=view&id=1_Bq2cLM5k9Fd2Q3IbilBN3op9PEFCc_u",
        "pokemon_type_id": "psychic,fighting",
        "pokemon_type_name": "超能力,格鬥"
    },
    {
        "id": "150",
        "zukan_sub_id": 2,
        "name": "超級超夢Ｙ",
        "pokemon_sub_name": "",
        "weight": 33,
        "height": 1.5,
        "file_name": "https://drive.google.com/uc?export=view&id=1bl8a1VwNZVclMJE72UR08X9X12PbfyLq",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
    {
        "id": "151",
        "zukan_sub_id": 0,
        "name": "夢幻",
        "pokemon_sub_name": "",
        "weight": 4,
        "height": 0.4,
        "file_name": "https://drive.google.com/uc?export=view&id=1JXgjGFaTsSgu7DMY80QbUxKNhMFT953E",
        "pokemon_type_id": "psychic",
        "pokemon_type_name": "超能力"
    },
];

export default {
    data
};